### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by tarek369** [megaboich/tv-shows-file-renamer#1]
(node:496) UnhandledPromiseRejectionWarning: Error: --slug is required
    at main (/usr/lib/node_modules/tv-shows-file-renamer/build/cli.js:32:15)
    at Object.<anonymous> (/usr/lib/node_modules/tv-shows-file-renamer/build/cli.js:75:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:496) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:496) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by megaboich** [comment]
Thanks @tarek369 for your bugreport.

It really looks like you do not specify required command line parameter. What is your command line?
